name: scheduleRenderbook
on:     
  push:
  schedule:     
     - cron: "15 8 * * *"  


jobs:
  bookdown:
    name: Render-Book
    runs-on:   ubuntu-latest #  macos-latest # macos USES 10 TIMES THE MINUTES
    steps:
      - uses: actions/checkout@v4
      # More detail here, https://github.com/r-lib/actions
      # It's possible to define R and pandoc version if desired
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c(
            "bookdown",
            "rmarkdown",
            "tidyverse",
            "leaflet",
            "DT",
            "ggplot2",
            "knitr",
            "htmltools",
            "kableExtra",
            "plotly",
            "sf",
            "viridis",
            "lubridate",
            "googledrive",
            "scales",
            "tidyr",
            "ggrepel"
          ))'

      - name: Render Book
        env: 
          GOOGLE_AUTHENTICATION_CREDENTIALS: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS }}
        run: Rscript -e 'rmarkdown::render("index.Rmd")'  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  
          publish_branch: gh-pages
          force_orphan: true
